---
- name: Testing andrewrothstein.jaeger
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'jaeger-agent version'
      ansible.builtin.command: jaeger-agent version
      changed_when: false
      register: jaegar_test_output
    - name: Output from 'jaeger-agent version'
      ansible.builtin.debug:
        msg: '{{ jaegar_test_output.stdout }}'
