---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/jaeger-agent version
    register: jaegar_test_output
  - name: jaeger-agent version
    debug:
      msg: '{{ jaegar_test_output.stdout }}'
