---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install in {{ jaeger_install_dir }}
  become: true
  stat:
    path: '{{ jaeger_install_dir }}'
  changed_when: false
  register: jaeger_binary
- when: not jaeger_binary.stat.exists
  block:
    - name: downloading {{ jaeger_url }} to {{ jaeger_tmp_tgz }}
      become: true
      become_user: root
      get_url:
        url: '{{ jaeger_url }}'
        dest: '{{ jaeger_tmp_tgz }}'
        mode: 0644
        checksum: '{{ jaeger_checksum }}'
    - name: unarchiving {{ jaeger_tmp_tgz }} to {{ jaeger_parent_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ jaeger_tmp_tgz }}'
        dest: '{{ jaeger_parent_install_dir }}'
        creates: '{{ jaeger_install_dir }}'
  always:
    - name: rm -f {{ jaeger_tmp_tgz }}
      become: true
      become_user: root
      file:
        path: '{{ jaeger_tmp_tgz }}'
        state: absent
- name: linking {{ jaeger_link_dir }} to {{ jaeger_install_dir }}
  become: true
  become_user: root
  file:
    src: '{{ jaeger_install_dir }}'
    dest: '{{ jaeger_link_dir }}'
    state: link
- name: linking apps in {{ jaeger_link_dir }} from {{ jaeger_parent_install_dir }}/bin
  become: true
  become_user: root
  with_items: '{{ jaeger_links }}'
  file:
    src: '{{ jaeger_link_dir }}/{{ item }}'
    dest: '{{ jaeger_parent_install_dir }}/bin/{{ item }}'
    state: link
